name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]
        php-versions: [ "8.2" ]
        phpunit-versions: [ "latest" ]

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: Update packages to fit PHP Version
        run: composer update --no-install

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: ./vendor/bin/phpunit
